jobs failed still run 2nd workflows

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -17,3 +17,6 @@ jobs:
 
       - name: Validate js code
         run: node  --check script.js
+
+      - name: fail job intentionally
+        run: exit 1 #means job fail if 0 then job passed
